import React from 'react';
import { FileText, Download, Printer, ShieldAlert, Sparkles, CheckCircle2 } from 'lucide-react';

export default function ReportsView({ overviewData }) {
  const handlePrint = () => {
    window.print();
  };

  const downloadCSV = () => {
    if (!overviewData || !overviewData.kpis) return;
    const rows = [
      ["Metric", "Value"],
      ["Average AQI", overviewData.kpis.avg_aqi],
      ["Average PM2.5", overviewData.kpis.avg_pm25],
      ["Average PM10", overviewData.kpis.avg_pm10],
      ["High Risk Area Pct", `${overviewData.kpis.high_risk_pct}%`],
      ["Total Respiratory Patients", overviewData.kpis.total_respiratory],
      ["Total Hospital Admissions", overviewData.kpis.total_hospital],
    ];
    const csvContent = "data:text/csv;charset=utf-8," + rows.map(e => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "india_air_pollution_executive_summary.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-[#121319] border border-[#222430] rounded-2xl p-5 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center space-x-3">
          <div className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-xl">
            <FileText className="w-6 h-6 text-amber-400" />
          </div>
          <div>
            <h2 className="text-lg font-black text-white uppercase tracking-wider">
              Executive Briefing & Strategic Report
            </h2>
            <p className="text-xs text-zinc-400">High-level policymaker summary, risk indices & mitigation roadmaps</p>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={downloadCSV}
            className="flex items-center space-x-2 bg-[#1b1c26] hover:bg-[#252838] border border-[#2e3144] text-amber-400 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer shadow-sm"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export CSV</span>
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center space-x-2 bg-gradient-to-r from-red-600 to-amber-500 hover:from-red-500 hover:to-amber-400 text-black px-4 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer shadow-[0_0_15px_rgba(245,158,11,0.3)]"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Report Document Container */}
      <div className="bg-[#121319] border border-[#222430] rounded-2xl p-8 space-y-6">
        <div className="border-b border-[#222430] pb-5 flex justify-between items-start">
          <div>
            <h3 className="text-xl font-black text-white uppercase">
              National Air Quality & Epidemiological Assessment
            </h3>
            <p className="text-xs text-zinc-400 mt-1">Generated by VayuNet AI Matrix Intelligence Core</p>
          </div>
          <span className="px-3 py-1 rounded bg-red-950/80 border border-red-800 text-red-400 font-mono text-xs font-bold">
            CONFIDENTIAL / POLICY USE
          </span>
        </div>

        {/* Executive Overview Points */}
        <div className="space-y-4 text-xs text-zinc-300 leading-relaxed">
          <h4 className="text-sm font-bold text-amber-400 uppercase tracking-wider">
            1. Key Takeaways & Urgent Diagnostics
          </h4>
          <p>
            Across monitored national air basins, the aggregated mean AQI stands at <strong className="text-white font-mono">{overviewData?.kpis?.avg_aqi ?? 274} AQI</strong>, with fine particulate PM2.5 concentrations exceeding NAAQS safe statutory thresholds by more than <strong className="text-red-400 font-mono">160%</strong>.
          </p>
          <p>
            Epidemiological tracking correlates pollution peaks with over <strong className="text-white font-mono">{overviewData?.kpis?.total_hospital?.toLocaleString() ?? '150,000+'}</strong> hospital admissions and <strong className="text-white font-mono">{overviewData?.kpis?.total_respiratory?.toLocaleString() ?? '260,000+'}</strong> acute respiratory consultations.
          </p>
        </div>

        {/* Strategic Directives */}
        <div className="space-y-3 pt-4 border-t border-[#222430]">
          <h4 className="text-sm font-bold text-amber-400 uppercase tracking-wider">
            2. Strategic Policy Recommendations
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 bg-[#161822] rounded-xl border border-[#232637]">
              <div className="flex items-center space-x-2 text-amber-400 font-bold text-xs mb-1">
                <CheckCircle2 className="w-4 h-4" />
                <span>Immediate Transport Electrification</span>
              </div>
              <p className="text-[11px] text-zinc-400">
                Phase-in heavy electric transit corridors in Tier-1 zones to cut localized NO2 and PM2.5 by ~28%.
              </p>
            </div>

            <div className="p-4 bg-[#161822] rounded-xl border border-[#232637]">
              <div className="flex items-center space-x-2 text-red-400 font-bold text-xs mb-1">
                <CheckCircle2 className="w-4 h-4" />
                <span>Dynamic Smog Emergency Rationing</span>
              </div>
              <p className="text-[11px] text-zinc-400">
                Trigger automated odd-even restrictions and industrial curtailments when 72h forecast AQI breaches 300.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
