[theme]
primaryColor = "#0284c7"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"

[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
